spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=${NEON_DB_USER}
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Forces the app to look for the system environment variable SENDGRID_API_KEY
# If it is missing, the application startup will fail immediately (preventing broken deployments)
sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.email.from-address=${SENDGRID_FROM_EMAIL}